



# COMMON
NUMBER_TASKS = 10
LOWER_BOUND = 0
UPPER_BOUND = 1
DIMENSIONS = 50


# LSA-MFEA 
H = 30
MAXEVALS = 100000 * NUMBER_TASKS
NUMBER_RMPS = int(NUMBER_TASKS * (NUMBER_TASKS-1) / 2)



# MFEA
NUMBER_SUBPOPULATION = 100
MFEA_VERSION = 2
NUMBER_CHILD = NUMBER_SUBPOPULATION * NUMBER_TASKS
NUMBER_POPULATON = NUMBER_SUBPOPULATION * NUMBER_TASKS
LOOP = 1000