# COMMON
NUMBER_TASKS = 10
LOWER_BOUND = 0
UPPER_BOUND = 1
DIMENSIONS = 50


# MFEA
NUMBER_SUBPOPULATION = 100
MFEA_VERSION = 1
NUMBER_CHILD = NUMBER_SUBPOPULATION * NUMBER_TASKS
NUMBER_POPULATON = NUMBER_SUBPOPULATION * NUMBER_TASKS
LOOP = 1500
rmp_mfea = 0.3

# LSA-MFEA
H = 30
MAXEVALS = LOOP * 100 * NUMBER_TASKS
NUMBER_RMPS = int(NUMBER_TASKS * (NUMBER_TASKS - 1) / 2)
